### PR TITLE
Update padding, corner radius and arrow shape of bubble coach marks

### PR DESCRIPTION
**Pull request by beatrizz**
This has been requested by a design team at Microsoft that uses these coach marks.

---

I'd like to release a new version of the library with this change and https://github.com/TouchType/CornedBeef/pull/42 (already merged) so I've included increasing the version code and version number in a separate commit.

Screenshots

mdpi:
bubble-mdpi-down
bubble-mdpi-up

hdpi:
bubble-hdpi-down
bubble-hdpi-up

xhdpi:
bubble-xhdpi-down
bubble-xhdpi-up

xxhdpi:
bubble-xxhdpi-down
bubble-xxhdpi-up

And on Jelly Bean, the lowest API emulator I could run:
bubble-jb-down
bubble-jb-up

### CODE REVIEW

**Review by vjgarciag96 — APPROVED** [review]
LGTM! 

Could it be possible to use vector drawables instead of `png`s per screen density? (maybe out of scope of this task if we already had `png`s per screen density)

**Comment by beatrizz** [comment]
@vjgarciag96 it's unfortunately not possible without bigger changes because the minimum Android API this library supports is 12 (3.1) and vector drawable support was added in API 21 (https://developer.android.com/guide/topics/graphics/vector-drawable-resources).

We could try with VectorDrawableCompat, but we'd have to add a dependency. I haven't checked if the library size will be bigger with the dependency or with the pngs. We might not be able to test in low APIs, because all emulators below API 16 that I can see in Android Studio are deprecated.

I'd rather leave it and think about it separately. We might want to increase the minimum API level, it's very very low!

**Comment by vjgarciag96** [comment]
> @vjgarciag96 it's unfortunately not possible without bigger changes because the minimum Android API this library supports is 12 (3.1) and vector drawable support was added in API 21 (https://developer.android.com/guide/topics/graphics/vector-drawable-resources).
> 
> We could try with VectorDrawableCompat, but we'd have to add a dependency. I haven't checked if the library size will be bigger with the dependency or with the pngs. We might not be able to test in low APIs, because all emulators below API 16 that I can see in Android Studio are deprecated.
> 
> I'd rather leave it and think about it separately. We might want to increase the minimum API level, it's very very low!

Sounds reasonable, thanks for the explanation!

**Review by praveendath92 — APPROVED** [review]

**Comment by beatrizz** [comment]
@praveendath92 I've tried to publish and there's a problem with a certificate: https://dev.azure.com/msresearch/SwiftKey/_build/results?buildId=579845&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ea098990-53e4-52aa-5a84-5ead7c5f17f2

Do you know how to fix it? Thanks!

**Comment by beatrizz** [comment]
2.0.5 has now been published. Thanks @praveendath92 !

**Pull request merged**
