### PR TITLE
Setup azure devops config for running all tests

### PR DESCRIPTION
**Pull request by praveendath92**
Adding configuration to run all tests on Azure DevOps. Since this is a public repo, we have the following additional steps 

- CI is disabled. Requires comment from a member of SwiftKey team to run the tests on a PR. 
- The job runs a hosted agent from Microsoft - disconnected from rest of SwiftKey stuff. 
- No service connections are in the job either. So, pipeline should have no extra privileges (Hence a duplicate script for spinning up the emulator)

### CODE REVIEW

**Comment by ojj11** [comment]
Given that this is a public repository, please ensure that we're following the best practices listed here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#validate-contributions-from-forks

I would recommend using the hosted agents rather than our SwiftKey ones. Similarly I would suggest either disallowing running on forks, or requiring team member to comment to run the suite

**Comment by praveendath92** [comment]
Default is to not allow running on forks but I will double check that. I will look into running on hosted agents

**Comment by ojj11** [comment]
First sentence of the link I sent:

> When you create a build pipeline, your pipeline is automatically triggered for pull requests from forks of your repository

**Comment by praveendath92** [comment]
That's true by default. We can override that in yaml config and also override all of it again in the job triggers to disallow. I disabled the job right now to require a team members comment to run

**Comment by praveendath92** [comment]
@JPumphrey, @ojj11  I disabled the job for now. Please hold off on the review. @tehmur and I will evaluate what's the best way to do this for public repos. Will report when it's ready for review again

**Comment by praveendath92** [comment]
@JPumphrey, @ojj11 This is now ready for review

**Pull request merged**
